# Generated by Django 5.2.7 on 2025-11-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(default='Mon - Fri Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_time',
            field=models.CharField(default='9 AM - 5 PM Default', max_length=50),
        ),
    ]
