# Generated by Django 5.2.7 on 2025-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctorprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_days',
            field=models.CharField(default='Mon-Fri Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_time',
            field=models.CharField(default='9 AM-5 PM Default', max_length=50),
        ),
    ]
