# Generated by Django 5.2.7 on 2025-11-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_doctorprofile_gender_patientprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='short_bio',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='short_bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
