# Generated by Django 5.2.7 on 2025-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctorprofile_short_bio_patientprofile_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='short_bio',
            field=models.TextField(default='Null', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(default='Null', max_length=3),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='short_bio',
            field=models.TextField(default='Null', max_length=300),
        ),
    ]
