# Generated by Django 5.2.7 on 2025-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_doctorprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='address',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='age',
            field=models.CharField(default='Null', max_length=20),
        ),
    ]
