# Generated by Django 5.2.7 on 2025-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctorprofile_address_doctorprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
