# Generated by Django 5.2.7 on 2025-11-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_patientprofile_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
