# Generated by Django 5.2.7 on 2025-11-07 17:48

import django.db.models.deletion
import pescription_manage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_doctorprofile_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pescription_manage.models.prescription_upload_path)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='users.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='users.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(blank=True, help_text='e.g., 500 mg or 5 ml', max_length=100)),
                ('times_per_day', models.PositiveSmallIntegerField(blank=True, default=1, help_text='How many times per day')),
                ('duration_days', models.PositiveIntegerField(blank=True, default=1, help_text='For how many days')),
                ('instruction', models.CharField(blank=True, help_text='e.g., After meal or Before bed', max_length=255)),
                ('prescription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pescription_manage.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
